[workspace]
resolver = "2"

members = [
    "moxin-runner",
    "moxin-protocol",
    "moxin-backend",
    "moxin-fake-backend",
]

[package]
name = "moxin"
version = "0.1.0"
edition = "2021"
description = "A desktop GUI client for downloading and chatting with AI LLMs"

[dependencies]
moxin-protocol = { path = "moxin-protocol" }
moxin-backend = { path = "moxin-backend" }
moxin-fake-backend = { path = "moxin-fake-backend" }

makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "rik" }

robius-open = { git = "https://github.com/project-robius/robius-open", rev = "b901523667d4a8bbb0bba3cd1ebcc0b94d33534e" }

chrono = "0.4"
directories = "5.0.1"
unicode-segmentation = "1.10.1"
anyhow = "1.0"
serde_json = "1.0"
serde = { version = "1.0.197", features = ["derive"] }
lipsum = "0.9"
rand = "0.8.5"


## Configuration for `cargo bundle`
[package.metadata.bundle]
identifier = "com.moxin-org.moxin"
long_description = """
Moxin is a desktop GUI client that lets you browse AI Large Language Models (LLMs), download them,
and run them locally to chat with the models.
Moxin is built using the Makepad UI framework (https://github.com/makepad/makepad)
and Project Robius platform abstractions (https://github.com/project-robius),
and currently runs on all three major desktop platforms: Windows, macOS, and Linux.
Moxin uses the wasmedge WASM runtime to locally run the AI models.
"""

## Configuration for `cargo packager`
[package.metadata.packager]
## This command downloads the key parts of wasmedge and installs them into the local ./wasmedge directory.
before-packaging-command = """
MAKEPAD=packaged cargo build --release \
&& mkdir -p ./wasmedge \
&& curl -sfL --show-error https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-0.13.5-darwin_arm64.tar.gz | bsdtar -xf- -C ./wasmedge \
&& mkdir -p ./wasmedge/WasmEdge-0.13.5-Darwin/plugin \
&& curl -sf --location --progress-bar --show-error https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasi_nn-ggml-0.13.5-darwin_arm64.tar.gz | bsdtar -xf- -C ./wasmedge/WasmEdge-0.13.5-Darwin/plugin \
"""
before-each-package-command = """
echo -e "\n\nPackaging '$CARGO_PACKAGER_FORMAT'\n\n" \
&& mkdir -p ./dist/Moxin.app/Contents/Frameworks \
&& tree ./dist \
"""
# && cp ./wasmedge/WasmEdge-0.13.5-Darwin/lib/libwasmedge.0.dylib ./dist/Moxin.app/Contents/Frameworks/ \
# && cp ./wasmedge/WasmEdge-0.13.5-Darwin/plugin/libwasmedgePluginWasiNN.dylib ./dist/Moxin.app/Contents/Frameworks/ \
# """
product_name = "Moxin"
identifier = "com.moxin-org.moxin"
category = "Utility"
publisher = "moxin-org"
icons = ["app_icon128x128.png"]
formats = ["all"]
out_dir = "./dist"

[package.metadata.packager.macos]
minimum_system_version = "11.0"
frameworks = [
    "./wasmedge/WasmEdge-0.13.5-Darwin/lib/libwasmedge.0.dylib",
    "./wasmedge/WasmEdge-0.13.5-Darwin/plugin/libwasmedgePluginWasiNN.dylib",
]

## Configuration for `cargo packager`'s generation of a macOS .dmg 
[package.metadata.packager.dmg]
background = "./Moxin macOS dmg background.png"
window_size = { width = 960, height = 540 }
app_position = { x = 200, y = 250 }
application_folder_position = { x = 760, y = 250 }
