[workspace]
resolver = "2"

members = [
    "moxin-protocol",
    "moxin-backend",
    "moxin-fake-backend",
]

[package]
name = "moxin"
version = "0.1.0"
edition = "2021"
description = "A desktop GUI client for downloading and chatting with AI LLMs"

[dependencies]
moxin-protocol = { path = "moxin-protocol" }
moxin-backend = { path = "moxin-backend" }
moxin-fake-backend = { path = "moxin-fake-backend" }

makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "rik" }

robius-open = { git = "https://github.com/project-robius/robius-open", rev = "b901523667d4a8bbb0bba3cd1ebcc0b94d33534e" }

chrono = "0.4"
directories = "5.0.1"
unicode-segmentation = "1.10.1"
anyhow = "1.0"
serde_json = "1.0"
serde = { version = "1.0.197", features = ["derive"] }
lipsum = "0.9"
rand = "0.8.5"


[package.metadata.bundle]
identifier = "com.moxin-org.moxin"
long_description = """
Moxin is a desktop GUI client that lets you browse AI Large Language Models (LLMs), download them,
and run them locally to chat with the models.
Moxin is built using the Makepad UI framework (https://github.com/makepad/makepad)
and Project Robius platform abstractions (https://github.com/project-robius),
and currently runs on all three major desktop platforms: Windows, macOS, and Linux.
Moxin uses the wasmedge WASM runtime to locally run the AI models.
"""
